// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OpenApiCommonModelMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from OpenApiCommonModelMessages.proto</summary>
public static partial class OpenApiCommonModelMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for OpenApiCommonModelMessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OpenApiCommonModelMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiBPcGVuQXBpQ29tbW9uTW9kZWxNZXNzYWdlcy5wcm90bypJChBQcm90b1Bh",
          "eWxvYWRUeXBlEhEKDVBST1RPX01FU1NBR0UQBRINCglFUlJPUl9SRVMQMhIT",
          "Cg9IRUFSVEJFQVRfRVZFTlQQMyrwAQoOUHJvdG9FcnJvckNvZGUSEQoNVU5L",
          "Tk9XTl9FUlJPUhABEhcKE1VOU1VQUE9SVEVEX01FU1NBR0UQAhITCg9JTlZB",
          "TElEX1JFUVVFU1QQAxIRCg1USU1FT1VUX0VSUk9SEAUSFAoQRU5USVRZX05P",
          "VF9GT1VORBAGEhYKEkNBTlRfUk9VVEVfUkVRVUVTVBAHEhIKDkZSQU1FX1RP",
          "T19MT05HEAgSEQoNTUFSS0VUX0NMT1NFRBAJEhsKF0NPTkNVUlJFTlRfTU9E",
          "SUZJQ0FUSU9OEAoSGAoUQkxPQ0tFRF9QQVlMT0FEX1RZUEUQC0JNCihjb20u",
          "eHRyYWRlci5wcm90b2NvbC5wcm90by5jb21tb25zLm1vZGVsQhxDb250YWlu",
          "ZXJDb21tb25Nb2RlbE1lc3NhZ2VzUAGgAQE="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoPayloadType), typeof(global::ProtoErrorCode), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// --- INTENSIVE COMMANDS 1 - 49
/// --- COMMON API 50 - 69
/// </summary>
public enum ProtoPayloadType {
  /// <summary>
  /// common intensive
  /// </summary>
  [pbr::OriginalName("PROTO_MESSAGE")] ProtoMessage = 5,
  /// <summary>
  /// common commands
  /// </summary>
  [pbr::OriginalName("ERROR_RES")] ErrorRes = 50,
  [pbr::OriginalName("HEARTBEAT_EVENT")] HeartbeatEvent = 51,
}

/// <summary>
/// COMMON error codes 1 - 99
/// </summary>
public enum ProtoErrorCode {
  /// <summary>
  /// Generic error.
  /// </summary>
  [pbr::OriginalName("UNKNOWN_ERROR")] UnknownError = 1,
  /// <summary>
  /// Message is not supported. Wrong message.
  /// </summary>
  [pbr::OriginalName("UNSUPPORTED_MESSAGE")] UnsupportedMessage = 2,
  /// <summary>
  /// Generic error.  Usually used when input value is not correct.
  /// </summary>
  [pbr::OriginalName("INVALID_REQUEST")] InvalidRequest = 3,
  /// <summary>
  /// Deal execution is reached timeout and rejected.
  /// </summary>
  [pbr::OriginalName("TIMEOUT_ERROR")] TimeoutError = 5,
  /// <summary>
  /// Generic error for requests by id.
  /// </summary>
  [pbr::OriginalName("ENTITY_NOT_FOUND")] EntityNotFound = 6,
  /// <summary>
  /// Connection to Server is lost or not supported.
  /// </summary>
  [pbr::OriginalName("CANT_ROUTE_REQUEST")] CantRouteRequest = 7,
  /// <summary>
  /// Message is too large.
  /// </summary>
  [pbr::OriginalName("FRAME_TOO_LONG")] FrameTooLong = 8,
  /// <summary>
  /// Market is closed.
  /// </summary>
  [pbr::OriginalName("MARKET_CLOSED")] MarketClosed = 9,
  /// <summary>
  /// Order is blocked (e.g. under execution) and change cannot be applied.
  /// </summary>
  [pbr::OriginalName("CONCURRENT_MODIFICATION")] ConcurrentModification = 10,
  /// <summary>
  /// Message is blocked by server.
  /// </summary>
  [pbr::OriginalName("BLOCKED_PAYLOAD_TYPE")] BlockedPayloadType = 11,
}

#endregion


#endregion Designer generated code
