// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OpenApiCommonMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from OpenApiCommonMessages.proto</summary>
public static partial class OpenApiCommonMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for OpenApiCommonMessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OpenApiCommonMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtPcGVuQXBpQ29tbW9uTWVzc2FnZXMucHJvdG8aIE9wZW5BcGlDb21tb25N",
          "b2RlbE1lc3NhZ2VzLnByb3RvIkkKDFByb3RvTWVzc2FnZRITCgtwYXlsb2Fk",
          "VHlwZRgBIAIoDRIPCgdwYXlsb2FkGAIgASgMEhMKC2NsaWVudE1zZ0lkGAMg",
          "ASgJIosBCg1Qcm90b0Vycm9yUmVzEjEKC3BheWxvYWRUeXBlGAEgASgOMhEu",
          "UHJvdG9QYXlsb2FkVHlwZToJRVJST1JfUkVTEhEKCWVycm9yQ29kZRgCIAIo",
          "CRITCgtkZXNjcmlwdGlvbhgDIAEoCRIfChdtYWludGVuYW5jZUVuZFRpbWVz",
          "dGFtcBgEIAEoBCJOChNQcm90b0hlYXJ0YmVhdEV2ZW50EjcKC3BheWxvYWRU",
          "eXBlGAEgASgOMhEuUHJvdG9QYXlsb2FkVHlwZToPSEVBUlRCRUFUX0VWRU5U",
          "QkIKImNvbS54dHJhZGVyLnByb3RvY29sLnByb3RvLmNvbW1vbnNCF0NvbnRh",
          "aW5lckNvbW1vbk1lc3NhZ2VzUAGgAQE="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::OpenApiCommonModelMessagesReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMessage), global::ProtoMessage.Parser, new[]{ "PayloadType", "Payload", "ClientMsgId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoErrorRes), global::ProtoErrorRes.Parser, new[]{ "PayloadType", "ErrorCode", "Description", "MaintenanceEndTimestamp" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoHeartbeatEvent), global::ProtoHeartbeatEvent.Parser, new[]{ "PayloadType" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ProtoMessage : pb::IMessage<ProtoMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoMessage> _parser = new pb::MessageParser<ProtoMessage>(() => new ProtoMessage());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::OpenApiCommonMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoMessage(ProtoMessage other) : this() {
    _hasBits0 = other._hasBits0;
    payloadType_ = other.payloadType_;
    payload_ = other.payload_;
    clientMsgId_ = other.clientMsgId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoMessage Clone() {
    return new ProtoMessage(this);
  }

  /// <summary>Field number for the "payloadType" field.</summary>
  public const int PayloadTypeFieldNumber = 1;
  private readonly static uint PayloadTypeDefaultValue = 0;

  private uint payloadType_;
  /// <summary>
  /// Contains id of ProtoPayloadType or other custom PayloadTypes (e.g. ProtoOAPayloadType)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PayloadType {
    get { if ((_hasBits0 & 1) != 0) { return payloadType_; } else { return PayloadTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      payloadType_ = value;
    }
  }
  /// <summary>Gets whether the "payloadType" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPayloadType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "payloadType" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayloadType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 2;
  private readonly static pb::ByteString PayloadDefaultValue = pb::ByteString.Empty;

  private pb::ByteString payload_;
  /// <summary>
  /// Serialized protobuf message that corresponds to payloadType
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_ ?? PayloadDefaultValue; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "payload" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPayload {
    get { return payload_ != null; }
  }
  /// <summary>Clears the value of the "payload" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payload_ = null;
  }

  /// <summary>Field number for the "clientMsgId" field.</summary>
  public const int ClientMsgIdFieldNumber = 3;
  private readonly static string ClientMsgIdDefaultValue = "";

  private string clientMsgId_;
  /// <summary>
  /// Request message id, assigned by the client that will be returned in the response
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientMsgId {
    get { return clientMsgId_ ?? ClientMsgIdDefaultValue; }
    set {
      clientMsgId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "clientMsgId" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasClientMsgId {
    get { return clientMsgId_ != null; }
  }
  /// <summary>Clears the value of the "clientMsgId" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearClientMsgId() {
    clientMsgId_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PayloadType != other.PayloadType) return false;
    if (Payload != other.Payload) return false;
    if (ClientMsgId != other.ClientMsgId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPayloadType) hash ^= PayloadType.GetHashCode();
    if (HasPayload) hash ^= Payload.GetHashCode();
    if (HasClientMsgId) hash ^= ClientMsgId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasPayloadType) {
      output.WriteRawTag(8);
      output.WriteUInt32(PayloadType);
    }
    if (HasPayload) {
      output.WriteRawTag(18);
      output.WriteBytes(Payload);
    }
    if (HasClientMsgId) {
      output.WriteRawTag(26);
      output.WriteString(ClientMsgId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasPayloadType) {
      output.WriteRawTag(8);
      output.WriteUInt32(PayloadType);
    }
    if (HasPayload) {
      output.WriteRawTag(18);
      output.WriteBytes(Payload);
    }
    if (HasClientMsgId) {
      output.WriteRawTag(26);
      output.WriteString(ClientMsgId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasPayloadType) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PayloadType);
    }
    if (HasPayload) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (HasClientMsgId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientMsgId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoMessage other) {
    if (other == null) {
      return;
    }
    if (other.HasPayloadType) {
      PayloadType = other.PayloadType;
    }
    if (other.HasPayload) {
      Payload = other.Payload;
    }
    if (other.HasClientMsgId) {
      ClientMsgId = other.ClientMsgId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PayloadType = input.ReadUInt32();
          break;
        }
        case 18: {
          Payload = input.ReadBytes();
          break;
        }
        case 26: {
          ClientMsgId = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PayloadType = input.ReadUInt32();
          break;
        }
        case 18: {
          Payload = input.ReadBytes();
          break;
        }
        case 26: {
          ClientMsgId = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ProtoErrorRes : pb::IMessage<ProtoErrorRes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoErrorRes> _parser = new pb::MessageParser<ProtoErrorRes>(() => new ProtoErrorRes());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoErrorRes> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::OpenApiCommonMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoErrorRes() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoErrorRes(ProtoErrorRes other) : this() {
    _hasBits0 = other._hasBits0;
    payloadType_ = other.payloadType_;
    errorCode_ = other.errorCode_;
    description_ = other.description_;
    maintenanceEndTimestamp_ = other.maintenanceEndTimestamp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoErrorRes Clone() {
    return new ProtoErrorRes(this);
  }

  /// <summary>Field number for the "payloadType" field.</summary>
  public const int PayloadTypeFieldNumber = 1;
  private readonly static global::ProtoPayloadType PayloadTypeDefaultValue = global::ProtoPayloadType.ErrorRes;

  private global::ProtoPayloadType payloadType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoPayloadType PayloadType {
    get { if ((_hasBits0 & 1) != 0) { return payloadType_; } else { return PayloadTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      payloadType_ = value;
    }
  }
  /// <summary>Gets whether the "payloadType" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPayloadType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "payloadType" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayloadType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "errorCode" field.</summary>
  public const int ErrorCodeFieldNumber = 2;
  private readonly static string ErrorCodeDefaultValue = "";

  private string errorCode_;
  /// <summary>
  /// Contains name of ProtoErrorCode or other custom ErrorCodes (e.g. ProtoCHErrorCode)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorCode {
    get { return errorCode_ ?? ErrorCodeDefaultValue; }
    set {
      errorCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "errorCode" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasErrorCode {
    get { return errorCode_ != null; }
  }
  /// <summary>Clears the value of the "errorCode" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearErrorCode() {
    errorCode_ = null;
  }

  /// <summary>Field number for the "description" field.</summary>
  public const int DescriptionFieldNumber = 3;
  private readonly static string DescriptionDefaultValue = "";

  private string description_;
  /// <summary>
  /// Error description
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Description {
    get { return description_ ?? DescriptionDefaultValue; }
    set {
      description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "description" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDescription {
    get { return description_ != null; }
  }
  /// <summary>Clears the value of the "description" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDescription() {
    description_ = null;
  }

  /// <summary>Field number for the "maintenanceEndTimestamp" field.</summary>
  public const int MaintenanceEndTimestampFieldNumber = 4;
  private readonly static ulong MaintenanceEndTimestampDefaultValue = 0UL;

  private ulong maintenanceEndTimestamp_;
  /// <summary>
  /// CS-10489 Epoch timestamp in second
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong MaintenanceEndTimestamp {
    get { if ((_hasBits0 & 2) != 0) { return maintenanceEndTimestamp_; } else { return MaintenanceEndTimestampDefaultValue; } }
    set {
      _hasBits0 |= 2;
      maintenanceEndTimestamp_ = value;
    }
  }
  /// <summary>Gets whether the "maintenanceEndTimestamp" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMaintenanceEndTimestamp {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "maintenanceEndTimestamp" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMaintenanceEndTimestamp() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoErrorRes);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoErrorRes other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PayloadType != other.PayloadType) return false;
    if (ErrorCode != other.ErrorCode) return false;
    if (Description != other.Description) return false;
    if (MaintenanceEndTimestamp != other.MaintenanceEndTimestamp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPayloadType) hash ^= PayloadType.GetHashCode();
    if (HasErrorCode) hash ^= ErrorCode.GetHashCode();
    if (HasDescription) hash ^= Description.GetHashCode();
    if (HasMaintenanceEndTimestamp) hash ^= MaintenanceEndTimestamp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasPayloadType) {
      output.WriteRawTag(8);
      output.WriteEnum((int) PayloadType);
    }
    if (HasErrorCode) {
      output.WriteRawTag(18);
      output.WriteString(ErrorCode);
    }
    if (HasDescription) {
      output.WriteRawTag(26);
      output.WriteString(Description);
    }
    if (HasMaintenanceEndTimestamp) {
      output.WriteRawTag(32);
      output.WriteUInt64(MaintenanceEndTimestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasPayloadType) {
      output.WriteRawTag(8);
      output.WriteEnum((int) PayloadType);
    }
    if (HasErrorCode) {
      output.WriteRawTag(18);
      output.WriteString(ErrorCode);
    }
    if (HasDescription) {
      output.WriteRawTag(26);
      output.WriteString(Description);
    }
    if (HasMaintenanceEndTimestamp) {
      output.WriteRawTag(32);
      output.WriteUInt64(MaintenanceEndTimestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasPayloadType) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PayloadType);
    }
    if (HasErrorCode) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorCode);
    }
    if (HasDescription) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
    }
    if (HasMaintenanceEndTimestamp) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MaintenanceEndTimestamp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoErrorRes other) {
    if (other == null) {
      return;
    }
    if (other.HasPayloadType) {
      PayloadType = other.PayloadType;
    }
    if (other.HasErrorCode) {
      ErrorCode = other.ErrorCode;
    }
    if (other.HasDescription) {
      Description = other.Description;
    }
    if (other.HasMaintenanceEndTimestamp) {
      MaintenanceEndTimestamp = other.MaintenanceEndTimestamp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PayloadType = (global::ProtoPayloadType) input.ReadEnum();
          break;
        }
        case 18: {
          ErrorCode = input.ReadString();
          break;
        }
        case 26: {
          Description = input.ReadString();
          break;
        }
        case 32: {
          MaintenanceEndTimestamp = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PayloadType = (global::ProtoPayloadType) input.ReadEnum();
          break;
        }
        case 18: {
          ErrorCode = input.ReadString();
          break;
        }
        case 26: {
          Description = input.ReadString();
          break;
        }
        case 32: {
          MaintenanceEndTimestamp = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///* Event that is sent from Open API proxy and can be used as criteria that connection is healthy when no other messages are sent by cTrader platform. Open API client can send this message when he needs to keep the connection open for a period without other messages longer than 30 seconds 
/// </summary>
public sealed partial class ProtoHeartbeatEvent : pb::IMessage<ProtoHeartbeatEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoHeartbeatEvent> _parser = new pb::MessageParser<ProtoHeartbeatEvent>(() => new ProtoHeartbeatEvent());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoHeartbeatEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::OpenApiCommonMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoHeartbeatEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoHeartbeatEvent(ProtoHeartbeatEvent other) : this() {
    _hasBits0 = other._hasBits0;
    payloadType_ = other.payloadType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoHeartbeatEvent Clone() {
    return new ProtoHeartbeatEvent(this);
  }

  /// <summary>Field number for the "payloadType" field.</summary>
  public const int PayloadTypeFieldNumber = 1;
  private readonly static global::ProtoPayloadType PayloadTypeDefaultValue = global::ProtoPayloadType.HeartbeatEvent;

  private global::ProtoPayloadType payloadType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoPayloadType PayloadType {
    get { if ((_hasBits0 & 1) != 0) { return payloadType_; } else { return PayloadTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      payloadType_ = value;
    }
  }
  /// <summary>Gets whether the "payloadType" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPayloadType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "payloadType" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayloadType() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoHeartbeatEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoHeartbeatEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PayloadType != other.PayloadType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPayloadType) hash ^= PayloadType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasPayloadType) {
      output.WriteRawTag(8);
      output.WriteEnum((int) PayloadType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasPayloadType) {
      output.WriteRawTag(8);
      output.WriteEnum((int) PayloadType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasPayloadType) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PayloadType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoHeartbeatEvent other) {
    if (other == null) {
      return;
    }
    if (other.HasPayloadType) {
      PayloadType = other.PayloadType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PayloadType = (global::ProtoPayloadType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PayloadType = (global::ProtoPayloadType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
